name: Release NudeShared

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

concurrency:
  group: nudeshared-release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gabriel20xx'

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version (patch)
        if: contains(github.event.head_commit.message, '[skip ci]') == false && github.actor != 'github-actions[bot]'
        run: |
          npm version patch -m "chore(release): %s [skip ci]"
          git push --follow-tags

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure scope registry mapping exists even if user removed .npmrc
          npm config set @gabriel20xx:registry https://npm.pkg.github.com
          npm publish --ignore-scripts=false
